### ISSUE TITLE
Отступы

### ISSUE THREAD

**Issue by OlegPasko** [IceBearGit/RubyHW#1]
https://github.com/IceBearGit/RubyHW/blob/1f0c9ce515b61bfd37a65c1305502d7639d423ea/HW1/tasks.rb#L8

1. https://github.com/rubocop-hq/ruby-style-guide#indentation отступы не табами, а по два спейса. В руби – только так )
```
# good
def some_method
  do_something
end
```

Между аргументами – так же спейс, но один:
Так: `even_odd_indexes_parser (arr)`

Табы, в принципе, вообще не используются для руби. Если есть IDE – просто ставь автозамену таба на два пробела.

Так же не стоит дела два абзаца.

ps. Я не буду писать однотипные замечания к каждой строчке. Просто экстраполируй замечание на все задачки )

**Comment by IceBearGit** [comment]
Привет. За отступы - спасибо. Исправлюсь.
