### ISSUE TITLE
Сортировка

### ISSUE THREAD

**Issue by OlegPasko** [IceBearGit/RubyHW#2]
https://github.com/IceBearGit/RubyHW/blob/1f0c9ce515b61bfd37a65c1305502d7639d423ea/HW1/tasks.rb#L42

Дословно это и подобная задачи выполнены. 

Но уверен, автор имел ввиду, и красивее было бы, отдать на выходе отсортированный массив. Мы пока за такое балы снимать не будем, но надо иметь ввиду.
Надо было слепить его, как минимум ) Был бы костыль, но задачу решило бы.

Почитай вот это:
https://ruby-doc.org/core-2.7.0/Array.html#method-i-sort
https://mixandgo.com/learn/ruby-sort-and-sort-by

Посмотри на вот эту реализацию:
https://stackoverflow.com/questions/42923549/ruby-sorting-even-and-odd-numbers-issue

Обрати внимание, что в руби есть .odd? и .even? методы.

**Comment by OlegPasko** [comment]
Хотя тут уже sort используется ) https://github.com/IceBearGit/RubyHW/blob/1f0c9ce515b61bfd37a65c1305502d7639d423ea/HW1/tasks.rb#L616

**Comment by IceBearGit** [comment]
я же учился по ходу ).  .odd? и .even? методы - тоже попали мне чуть позже, потому и не исправлял задачу. решено же верно. Можно  както попробовать челендж, кто больше вариантов решений одной задачи придумает :-)
