### ISSUE TITLE
Повнимательней

### ISSUE THREAD

**Issue by OlegPasko** [IceBearGit/RubyHW#4]
https://github.com/IceBearGit/RubyHW/blob/1f0c9ce515b61bfd37a65c1305502d7639d423ea/HW1/tasks.rb#L197

В условии же надо посчитать кол-во элементов )
Но т.к. я видел, что count уже использовалось, скорее всего, просто невнимательно прочитано условие... 
...но если бы это было банковское приложение? :)

**Comment by IceBearGit** [comment]
Сорян, косяк. Будем исправляться.
