### ISSUE TITLE
Классный тамагочи

### ISSUE THREAD

**Issue by OlegPasko** [IceBearGit/RubyHW#9]
https://github.com/IceBearGit/RubyHW/blob/2cbde16ccd77330d713feffaecdfebd0d2bb8f34/HW2/krokokot/tamagochi.rb#L147

Отлично! ) 
Предлагаю подумать, как можно этот код сделать более DRY. Не срочно. Отложить в голове и потом вернуться.

**Comment by IceBearGit** [comment]
Thanks
